# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-30 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_gasStation_map', '0002_auto_20200720_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='calModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startX', models.FloatField()),
                ('startY', models.FloatField()),
                ('economy', models.FloatField(verbose_name='Rendimiento de tu automovil (km/lt)')),
                ('money', models.FloatField(verbose_name='Cuanto dinero tienes para comprar gasolina (MXN)')),
            ],
        ),
        migrations.AlterField(
            model_name='plotmodel',
            name='end_date',
            field=models.DateField(default='2020-07-30', verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='plotmodel',
            name='initial_date',
            field=models.DateField(default='2020-07-30', verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='plotmodel',
            name='state',
            field=models.CharField(choices=[('AG', 'Aguascalientes'), ('BC', 'Baja California'), ('BS', 'Baja California Sur'), ('CM', 'Campeche'), ('CS', 'Chiapas'), ('CH', 'Chihuahua'), ('DF', 'Ciudad de México'), ('CO', 'Coahuila'), ('CL', 'Colima'), ('DG', 'Durango'), ('GJ', 'Guanajuato'), ('GR', 'Guerrero'), ('HG', 'Hidalgo'), ('JA', 'Jalisco'), ('MX', 'Estado de México'), ('MI', 'Michoacán'), ('MO', 'Morelos'), ('NA', 'Nayarit'), ('NL', 'Nuevo Leon'), ('OA', 'Oaxaca'), ('PU', 'Puebla'), ('QT', 'Querétaro'), ('QR', 'Quintana Roo'), ('SL', 'San Luis Potosí'), ('SI', 'Sinaloa'), ('SO', 'Sonora'), ('TB', 'Tabasco'), ('TM', 'Tamaulipas'), ('TL', 'Tlaxcala'), ('VE', 'Veracruz'), ('YU', 'Yucatan'), ('ZA', 'Zacatecas')], max_length=20),
        ),
    ]
